config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in', to: redirect('/'), as: :new_user_session
    get 'sign_out', to: redirect('/'), as: :destroy_user_session
  end

  root to: 'plays#index', date: 'today'

  get 'lf' => 'application#lastfm'
  post 'lf' => 'application#lastfm'
  get 'mb' => 'application#musicbrainz'

  resources :playlists, only: [:index, :show]
  resources :playlist_recordings, only: [:create]

  resources :plays, only: [:index, :create]

  resources :artists, only: [:show, :index, :update] do
    collection do
      get :roster
    end
  end

  resources :releases, only: [:show, :index, :update] do
    collection do
      get :search
      get :import
      post :import
    end
  end

  resources :recordings, only: [:index, :show, :update]
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :recording
  belongs_to :release

  validates_uniqueness_of :played_at
  validates_presence_of :recording, :played_at

  def self.icon
    "<i class='fa-duotone fa-circle-play'></i>"
  end

  def self.latest_play_utc
    Play.order("played_at").last.played_at.to_i
  end

  def self.ranked(query_params={})
    sql = <<-SQL.strip_heredoc
      SELECT plays.id,
        plays.played_at#{at_time_zone} as played_at,
        plays.user_id,
        played_releases.overall_rank as release_rank,
        played_releases.t_value as release_t_value,
        played_recordings.num_plays,
        releases.id           as release_id,
        releases.status       AS status,
        releases.year         AS year,
        releases.name         AS release_name,
        recordings.length,
        recordings.name       AS name,
        recordings.id         AS recording_id,
        recordings.category   AS category
        #{artist_subselects}
      FROM plays
      JOIN played_releases    ON played_releases.release_id = plays.release_id
      JOIN releases           ON releases.id = plays.release_id
      JOIN played_recordings  ON played_recordings.recording_id = plays.recording_id
      JOIN recordings         ON recordings.id = plays.recording_id
      JOIN joined_recording_artists AS _artists ON _artists.recording_id = plays.recording_id
      #{filter(query_params)}
      #{set_order('plays', query_params)}
    SQL
    sql += "LIMIT #{query_params[:limit]} " if query_params[:limit]
    sql += "OFFSET #{query_params[:offset]} " if query_params[:offset]
    find_by_sql(sql)
  end

  def self.filter(params)
    sql = []
    sql << filter_artists(params) if params[:artist_id].present?
    sql << filter_enum(Recording, 'category', params[:category], 'recordings.category') if params[:category].present?
    sql << filter_enum(Release, 'status', params[:status], 'releases.status') if params[:status].present?
    sql << filter_year(params) if params[:year].present?
    sql << filter_by_date(params) if params[:date].present?
    sql << filter_time_played_at(params) if %i(play_year play_month play_day play_dow play_hour).any? { |k| params.keys.include?(k) }
    sql << Play.sanitize_sql(["played_releases.t_value = ?", params[:t]]) if params[:t].present?
    sql = [Play.sanitize_sql(["plays.release_id = ?", params[:release_id]])] if params[:release_id].present?
    sql = [Play.sanitize_sql(["plays.recording_id = ?", params[:recording_id]])] if params[:recording_id].present?
    return if sql.empty?
    "WHERE #{sql.join(' AND ')}"
  end

  def self.filter_by_date(query_params)
    date       = query_params[:date].to_date
    end_date   = query_params.key?(:end_date) ? query_params[:end_date].to_date : date
    start_date = (date.beginning_of_day + 4.hours).utc
    end_date   = (end_date.end_of_day + 4.hours).utc
    Recording.sanitize_sql(["plays.played_at#{at_time_zone} BETWEEN ? AND ?", start_date, end_date])
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :parse_params, only: %i(index)

  def index
    @page_title = "Plays"
    @plays = Play.ranked(query).paginate(per_page: per_page, page: params[:page])
  end

  def create
    prev = Play.last
    recording = if params[:recording_id].present?
      Recording.find(params[:recording_id])
    else
      Recording.find(prev.recording_id + 1)
    end

    at = if params[:use_time_params].present? && params[:recording_id].present?
      at = Time.local(params[:year],params[:month],params[:day],params[:hour],params[:minute],0)
    else
      at = Time.at(prev.played_at + recording.length/1000)
    end

    Play.create(
      played_at: at,
      recording_id: recording.id,
      release_id: recording.releases.first.id
    )
    refresh_db_views
    redirect_to params[:form_redirect]
  end

  private

  def parse_params
    super
    query[:date] = Date.today.strftime('%Y%m%d') if query[:date] == 'today'
  end

  def per_page
    query[:date] ? 1000 : 30
  end
end

app/views/plays/_plays.html.erb
<% if plays.any? %>
  <table id='plays'>
    <% show_headers = local_assigns.fetch(:show_headers) { true } %>
    <% calendar_column = local_assigns.fetch(:calendar_column) { !query[:date].present? } %>
    <% max_plays = plays.max{|a,b| a.num_plays <=> b.num_plays}.num_plays %>
    <% max_width = max_plays > 10 ? max_plays : 10 %>

    <% if show_headers %>
      <tr class='plays-headers'>
        <th class='category'></th>
        <%= render partial: 'shared/tables/headers/played_at', locals: { calendar_column: calendar_column, link_name: 'played at' } %>
        <%= render partial: 'shared/tables/headers/name', locals: { prefix: 'artist' } %>
        <th class='play-length'><%= link_to 'length', plays_path(with_existing_query(:order, toggle_order('length'))) %></th>
        <%= render partial: 'shared/tables/headers/name' %>
        <th class='rank'></th>
        <th class='release-name'>release name</th>
        <th class='release-status'></th>
        <%= render partial: 'shared/tables/headers/year' %>
        <th class='rank-num'></th>
        <th class='num-plays'>total plays</th>
      </tr>
    <% else %>
      <tr><th></th></tr>
    <% end %>

    <% plays.each do |play| %>
      <tr id="play_<%= play.id %>">
        <td>
          <%= link_to releases_path(category: Release.categories.key(play.category)) do %>
            <div class='badge <%= Release.categories.key(play.category) %>'></div>
          <% end %>
        </td>
        <%= render partial: 'shared/links/timestamp', object: play.played_at, locals: { calendar_column: calendar_column, use_highlight: false, color: 'yellow' } %>
        <td class='artist-name'><%= render partial: 'shared/links/artist_names', locals: { thing: play } %></td>
        <td class='r'>
          <% length = Recording.display_length(play.length) %>
          <% min_length = length.delete(':') %>
          <%= link_to length, recordings_path(with_existing_query.merge(length_min: min_length, length_max: min_length)) %>
        </td>
        <td class='recording-name'><%= link_to play.name, recording_path(play.recording_id) %></td>
        <td><%= render partial: 'shared/links/rank', object: play.release_rank, locals: { t_value: play.release_t_value, obj_path: 'releases' } %></td>
        <td class='release-name'><%= link_to play.release_name, release_path(play.release_id) %></td>
        <td><%= render partial: 'shared/links/status', object: Release.statuses.key(play.status) %></td>
        <td><%= link_to play.year, plays_path(year: play.year) %></td>
        <td><%= play.release_rank %></td>
        <td><%= render partial: 'shared/num_plays_chart', locals: { collection: plays, record: play } %></td>
      </tr>
    <% end %>
  </table>

<% end %>

app/views/plays/index.html.erb
<% if query[:date].present? %>
  <% date = query[:date].to_date %>
  <% prev_date = date - 1 %>
  <% next_date = date + 1 %>
  <section id='play-date'>
    <h2>
      <%= render partial: 'shared/links/delete', object: with_existing_query(:date, query[:date]) %>
      <%= link_to prev_date.strftime('%-d'), plays_path(with_existing_query(:date, prev_date.strftime('%Y%m%d'))), class: 'diminished' %>
      <%= date.strftime("%a %B") %> <%= link_to date.day.ordinalize, plays_path(date: date.strftime('%Y%m%d')), class: 'bold' %>, <%= date.strftime('%Y (%j)') %>
      <%= link_to next_date.strftime('%-d'), plays_path(with_existing_query(:date, next_date.strftime('%Y%m%d'))), class: 'diminished' %>
    </h2>
  </section>
<% end %>
<%= render partial: 'shared/links/badge_filters' %>
<%= render partial: 'shared/links/played_at' %>
<%= render partial: 'shared/links/years' %>
<%= render partial: 'shared/links/artist' %>
<%= render partial: 'shared/order' %>

<section id='plays-list'>
  <%= render partial: 'plays/plays', object: @plays %>
  <%= will_paginate @plays if @plays.respond_to? :total_pages %>
</section>