config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in', to: redirect('/'), as: :new_user_session
    get 'sign_out', to: redirect('/'), as: :destroy_user_session
  end

  root to: 'plays#index', date: 'today'

  get 'lf' => 'application#lastfm'
  post 'lf' => 'application#lastfm'
  get 'mb' => 'application#musicbrainz'

  resources :playlists, only: [:index, :show]
  resources :playlist_recordings, only: [:create]

  resources :plays, only: [:index, :create]

  resources :artists, only: [:show, :index, :update] do
    collection do
      get :roster
    end
  end

  resources :releases, only: [:show, :index, :update] do
    collection do
      get :search
      get :import
      post :import
    end
  end

  resources :recordings, only: [:index, :show, :update]
end

app/views/shared/_alerts.html.erb
<section id='alerts'>
  <%= render partial: 'plays/plays', object: Play.ranked(limit: 1, order: 'recently-played'), locals: { calendar_column: true, show_headers: false } %>
</section>

app/views/shared/_controls.html.erb
<section id='controls'>
  <section id='local'>
    <%= render partial: 'artists/forms/edit', locals: { artist: @artist } if @artist.present? %>
    <%= render partial: 'releases/forms/edit', locals: { release: @release } if @release.present? %>
    <%= render partial: 'recordings/forms/edit', locals: { recording: @recording } if @recording.present? %>
  </section>
  <section id='global'>
    <%= render partial: 'plays/forms/new' %>
    <%= render partial: 'releases/forms/import' %>
    <%= button_to "Sign in with Spotify", user_spotify_omniauth_authorize_path %>
  </section>
</section>

app/views/shared/_graph.html.erb
<%
  start_num = local_assigns.fetch(:start_num) { 2006 }
  end_num = local_assigns.fetch(:end_num) { Date.today.year }
  column_count = local_assigns.fetch(:column_count) { end_num - start_num + 1 }
  max_height = local_assigns.fetch(:max_height, 250)
  category = local_assigns.fetch(:category, 'grey')
%>
<figure aria-hidden="true">
  <div class="graph" style="grid:repeat(10, auto) / repeat(<%= column_count %>, auto)">
    <% (start_num..end_num).each_with_index do |i, index| %>
      <% current = graph.find { |j| j.year.to_i == i } %>
      <% value = current.nil? ? 0 : current.play_count %>
      <div class="graph-bar <%= category %>" style="grid-column:<%= index+1 %>;--h:<%= value.to_f / max_height * 100 %>%"></div>
      <span class="graph-label <%= 'bold' if value > max_height %>"><%= value unless value == 0 %></span>
    <% end %>
    <% (start_num..end_num).each_with_index do |i, index| %>
      <span class="graph-year"><%= i % 3 == end_num % 3 ? i : nil %></span>
    <% end %>
  </div>
</figure>

app/views/shared/_nav.html.erb
<section id='nav'>
  <h2>
    <%= link_to 'Recordings', recordings_path, class: (params[:controller] == 'recordings' ? 'active' : '') %>
    <%= link_to 'Releases', releases_path, class: (params[:controller] == 'releases' ? 'active' : '') %>
    <%= link_to 'Artists', artists_path, class: (params[:controller] == 'artists' ? 'active' : '') %>
    <%= link_to 'Plays', root_path, class: (params[:controller] == 'plays' ? 'active' : '') %>
    <%= link_to 'Next', lf_path(redirect: @current_path) %>
    <span id='artist-search'>
      <%= render partial: 'shared/forms/name_search', locals: { obj_path: :artists, show_text_field_value: false, show_label: false } %>
    </span>
  </h2>
</section>

app/views/shared/_num_plays_chart.html.erb
<% attribute = local_assigns.fetch(:attribute) { 'num_plays' } %>
<% max_plays = collection.max{|a,b| a.num_plays <=> b.num_plays}.num_plays %>
<% max_width = max_plays > 10 ? max_plays : 10 %>
<% color = local_assigns.fetch(:color) { 'black' } %>

<% if record.send(attribute).to_i > 0 %>
  <%= link_to recordings_path(plays: record.send(attribute)) do %>
    <div class='play_chart_container <%= color %>' style='width:<%= (record.send(attribute).to_i.to_f/max_width)*100+10 %>px'>
      <%= record.send(attribute) %>
    </div>
  <% end %>
<% else %>
  0
<% end %>

app/views/shared/_order.html.erb
<% if query[:order] %>
  <section>
    <%= render partial: 'shared/links/delete', object: with_existing_query.except(:order) %> <%= query[:order] %>
  </section>
<% end %>

app/views/shared/_time_played_chart.html.erb
<%
  attribute = local_assigns.fetch(:attribute) { 'time_played' }
  max_plays = defined?(collection) ? collection.max{|a,b| (a.send(attribute) || 0) <=> (b.send(attribute) || 0)}.send(attribute).to_i/60000 : 2500
  max_width = max_plays > 10 ? max_plays : 10
  play_time = time_in_hours(record.send(attribute))
  div_class = 'play_chart_container '
  div_class += local_assigns.fetch(:color) { 'black' }
  div_class += ' unplayed' if play_time == '0.0'
%>
<div class='<%= div_class %>' style='width:<%= (play_time.to_f*100/max_width) + 30 %>px'>
  <%= play_time %>
</div>