config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in', to: redirect('/'), as: :new_user_session
    get 'sign_out', to: redirect('/'), as: :destroy_user_session
  end

  root to: 'plays#index', date: 'today'

  get 'lf' => 'application#lastfm'
  post 'lf' => 'application#lastfm'
  get 'mb' => 'application#musicbrainz'

  resources :playlists, only: [:index, :show]
  resources :playlist_recordings, only: [:create]

  resources :plays, only: [:index, :create]

  resources :artists, only: [:show, :index, :update] do
    collection do
      get :roster
    end
  end

  resources :releases, only: [:show, :index, :update] do
    collection do
      get :search
      get :import
      post :import
    end
  end

  resources :recordings, only: [:index, :show, :update]
end

app/views/shared/links/_artist.html.erb
<% if @filtered_artists %>
  <h2>
    <%= render partial: 'shared/links/delete', object: with_existing_query(:artist_id, query[:artist_id]) %>
    <% artist_links = [] %>
    <% @filtered_artists.each do |artist| %>
      <% artist_links << link_to(artist.name, artist_path(artist.id)) %>
    <% end %>
    <%= raw(artist_links.join(", ")) %>
    <%= render partial: 'shared/links/controller_switch', locals: { link_params: { artist_id: query[:artist_id], order: 'most-played' } } %>
  </h2>
<% end %>

app/views/shared/links/_artist_icon.html.erb
<span class='badge'>
  <%= link_to artist_path(artist_icon) do %>
    <%= raw(Artist.icon) %>
  <% end %>
</span>

app/views/shared/links/_artist_names.html.erb
<% obj_path = thing.class.name.downcase.pluralize %>
<% artist_links = [] %>
<% thing.json_artists.each do |artist| %>
  <% artist_icon = render partial: 'shared/links/artist_icon', object: artist['id'] %>
  <% order = obj_path == 'plays' ? 'recently-played' : 'most-played' %>
  <% artist_name = link_to(artist['name'], send("#{obj_path}_path", with_existing_query(:artist_id, artist['id']).merge(order: order))) %>
  <% artist_links << [artist_icon, artist_name].join  %>
<% end %>
<%= raw(artist_links.join(", ")) %>

app/views/shared/links/_badge_filters.html.erb
<section class="badge-filters">
  <div class='link-set'>
    <% status_class = params[:controller] == 'plays' ? Release : params[:controller].singularize.classify.constantize %>
    <% category_class = params[:controller] == 'plays' ? Recording : params[:controller].singularize.classify.constantize %>
    <% tiers = (1..9).to_a %>
    <% applied_rank = tiers.delete(params[:t].try(:to_i)) || params[:t].try(:to_i) %>
    <% applied_statuses = query[:status].present? ? query[:status].split(',') : [] %>
    <% applied_categories = query[:category].present? ? query[:category].split(',') : [] %>
    <% rank_obj_path = params[:controller] == 'artists' ? params[:controller] : 'releases' %>

    <% if applied_rank.present? || applied_statuses.any? || applied_categories.any? %>
      <%= render partial: 'shared/links/delete', object: with_existing_query.except(:t, :status, :category) %>
    <% end %>
    <% if applied_rank.present? %>
      <%= render partial: 'shared/links/rank', locals: { t_value: applied_rank, except: %i(date), obj_path: rank_obj_path } %>
    <% end %>
    <% applied_statuses.each do |status| %>
      <%= render partial: 'shared/links/status', locals: { status: status, except: %i(date) } %>
    <% end %>
    <% applied_categories.each do |category| %>
      <%= render partial: 'shared/links/category', locals: { category: category, except: %i(date) } %>
    <% end %>

    <% if applied_rank.present? || applied_statuses.any? || applied_categories.any? %>
      <span> | </span>
    <% end %>

    <% tiers.each do |t_value| %>
      <%= render partial: 'shared/links/rank', locals: { t_value: t_value, except: %i(date), obj_path: rank_obj_path } %>
    <% end %>
    <% (10..22).to_a.each do |i| %>
      <div class='badge t_value'>
        <%= link_to i, send("#{rank_obj_path}_path", with_existing_query(:t, i).except(:date)), class: 't_value' %>
      </div>
    <% end %>
    <% (status_class.statuses.keys - applied_statuses).each do |status| %>
      <%= render partial: 'shared/links/status', locals: { status: status, except: %i(date) } %>
    <% end %>
    <% (category_class.categories.keys - applied_categories).each do |category| %>
      <%= render partial: 'shared/links/category', locals: { category: category, except: %i(date) } %>
    <% end %>

    <% if query[:category] || query[:status] %>
      <%= render partial: 'shared/links/controller_switch', locals: { link_params: query.slice(:category, :status) } %>
    <% end %>
  </div>
</section>

app/views/shared/links/_category.html.erb
<% thing = local_assigns.fetch(:thing) { nil } %>
<% except = local_assigns.fetch(:except) { [] } %>
<% category = thing&.category || category %>
<% obj_path = thing ? thing.class.name.downcase.pluralize : local_assigns.fetch(:obj_path) { params[:controller] } %>
<% obj_class = obj_path.to_s.singularize.classify.constantize %>

<span class='badge <%= category %>'>
  <% except += %i(artist_id release_id) %>
  <%= link_to send("#{obj_path}_path", with_existing_query(:category, category).except(*except)) do %>
    <i class='<%= obj_class.status_icons(nil) %>'></i>
  <% end %>
</span>

app/views/shared/links/_controller_switch.html.erb
<% link_params = local_assigns.fetch(:link_params) { {} } %>

<% if !link_params.keys.include?(:artist_id) %>
  <span class='badge artists'>
    <% if params[:controller] == 'artists' %>
      <%= raw(Artist.icon) %>
    <% else %>
      <%= link_to artists_path(link_params) do %>
        <%= raw(Artist.icon) %>
      <% end %>
    <% end %>
  </span>
<% end %>
<span class='badge releases'>
  <% if params[:controller] == 'releases' %>
    <%= raw(Release.icon) %>
  <% else %>
    <%= link_to releases_path(link_params) do %>
      <%= raw(Release.icon) %>
    <% end %>
  <% end %>
</span>
<span class='badge recordings'>
  <% if params[:controller] == 'recordings' %>
    <%= raw(Recording.icon) %>
  <% else %>
    <%= link_to recordings_path(link_params) do %>
      <%= raw(Recording.icon) %>
    <% end %>
  <% end %>
</span>
<% if !ApplicationRecord::PLAYED_AT_QUERY_KEYS.any? { |k| query[k].present? } %>
  <span class='badge plays'>
    <% if params[:controller] == 'plays' %>
      <%= raw(Play.icon) %>
    <% else %>
      <%= link_to plays_path(link_params.except(:order)) do %>
        <%= raw(Play.icon) %>
      <% end %>
    <% end %>
  </span>
<% end %>

app/views/shared/links/_delete.html.erb
<span class='badge delete'>
  <%= link_to send("#{params[:controller]}_path", delete) do %>
    <i class='fa-duotone fa-circle-minus'></i>
  <% end %>
</span>

app/views/shared/links/_played_at.html.erb
<% if %i(play_year play_month play_day play_dow play_hour).any? { |k| query.key?(k) } %>
  <section class='played-at-times'>
    <% if %i(play_year play_month play_day).any? { |k| query.key?(k) } %>
      <%= render partial: 'shared/links/delete', object: with_existing_query.except(:play_year, :play_month, :play_day) %>
    <% end %>

    <% years = query[:play_year]&.split(',')&.sort || [] %>
    <% months = query[:play_month]&.split(',')&.sort || [] %>
    <% days = query[:play_day]&.split(',')&.sort || [] %>

    <% year_part = years.length == 1 ? years.first : Date.today.year %>
    <% month_part = months.length == 1 ? months.first.rjust(2, '0') : '01' %>
    <% day_part = days.length == 1 ? days.first.rjust(2, '0') : '01' %>
    <% link_format = days.length == 1 ? '%-d' : months.length == 1 ? '%b' : '%Y' %>
    <% time_adv = days.length == 1 ? :day : months.length == 1 ? :month : :year %>

    <% if years.length == 1 || months.length == 1 || days.length == 1 %>
      <% link_to_date = Date.parse("#{year_part}#{month_part}#{day_part}") - 1.send(time_adv) %>
      <% link_params = {} %>
      <% link_params[:play_year] = link_to_date.year if years.length == 1 %>
      <% link_params[:play_month] = link_to_date.month if months.length == 1 %>
      <% link_params[:play_day] = link_to_date.day if days.length == 1 %>
      <%= link_to link_to_date.strftime(link_format), send("#{params[:controller]}_path", with_existing_query.merge(link_params)), class: :diminished %>
    <% end %>

    <% if years %>
      <% years.each do |year| %>
        <%= link_to year, send("#{params[:controller]}_path", with_existing_query(:play_year, year)), class: 'bold' %>
      <% end %>
    <% end %>

    <% if query[:play_month] %>
      <% months.each do |month| %>
        <%= link_to Date::ABBR_MONTHNAMES[month.to_i], send("#{params[:controller]}_path", with_existing_query(:play_month, month)), class: 'bold' %>
      <% end %>
    <% end %>

    <% if query[:play_day] %>
      <% query[:play_day].split(',').each do |day| %>
        <%= link_to day, send("#{params[:controller]}_path", with_existing_query(:play_day, day)), class: 'bold' %>
      <% end %>
    <% end %>

    <% if years.length == 1 || months.length == 1 || days.length == 1 %>
      <% link_to_date = Date.parse("#{year_part}#{month_part}#{day_part}") + 1.send(time_adv) %>
      <% link_params = {} %>
      <% link_params[:play_year] = link_to_date.year if years.length == 1 %>
      <% link_params[:play_month] = link_to_date.month if months.length == 1 %>
      <% link_params[:play_day] = link_to_date.day if days.length == 1 %>
      <%= link_to link_to_date.strftime(link_format), send("#{params[:controller]}_path", with_existing_query.merge(link_params)), class: :diminished %>
    <% end %>

    <% if query[:play_hour] %>
      <%= render partial: 'shared/links/delete', object: with_existing_query.except(:play_hour) %>
      <% query[:play_hour].split(',').each do |hour| %>
        <% tmp = hour.to_i - 12 %>
        <% link_name = "#{hour.to_i}am" if tmp < 0 %>
        <% link_name = "12pm" if tmp == 0 %>
        <% link_name = "12am" if tmp == -12 %>
        <% link_name = "#{tmp}pm" if tmp > 0 %>
        <%= link_to link_name, send("#{params[:controller]}_path", with_existing_query(:play_hour, hour)), class: 'bold' %>
      <% end %>
    <% end %>

    <% if query[:play_dow] %>
      <%= render partial: 'shared/links/delete', object: with_existing_query.except(:play_dow) %>
      <% (0..6).to_a.each do |i| %>
        <% name = Date::DAYNAMES[i][0..2] %>
        <% link_class = query[:play_dow].split(',').map(&:to_i).include?(i) ? 'bold' : 'diminished' %>
        <%= link_to name, send("#{params[:controller]}_path", with_existing_query(:play_dow, i)), class: link_class %>
      <% end %>
    <% end %>

    <%= render partial: 'shared/links/controller_switch', locals: { link_params: query.slice(:play_year, :play_month, :play_day, :play_dow, :play_hour) } %>
  </section>
<% end %>

app/views/shared/links/_rank.html.erb
<% as_badge = local_assigns.fetch(:as_badge) { true } %>
<% t_value = local_assigns.fetch(:t_value) { 10 } %>
<% except = local_assigns.fetch(:except) { [] } %>
<% obj_path = local_assigns.fetch(:obj_path) { params[:controller] } %>
<% link_name = as_badge ? '' : rank %>

<% if as_badge %>
  <div class='badge t<%= t_value %>'>
<% end %>

<% if t_value < 23 %>
  <% if link_name.present? %>
    <%= link_to link_name, send("#{obj_path}_path", with_existing_query(:t, t_value).except(*except)), class: 't_value' %>
  <% else %>
    <%= link_to send("#{obj_path}_path", with_existing_query(:t, t_value).except(*except)), class: 't_value' do %>
      <% if t_value < 10 %>
        <i class='fa-duotone fa-album'></i>
      <% else %>
        <%= t_value %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <%= link_to link_name, send("#{obj_path}_path", order: 'most-played', page: (t_value.to_i/40.0).ceil), class: 't_value' %>
<% end %>

<% if as_badge %>
  </div>
<% end %>

app/views/shared/links/_releases.html.erb
<% release_links = [] %>
<% thing.json_releases.each do |release| %>
  <% release_links << link_to(release['name'], release_path(release['id'])) %>
<% end %>
<%= raw(release_links.join(", ")) %>

app/views/shared/links/_status.html.erb
<% thing = local_assigns.fetch(:thing) { nil } %>
<% except = local_assigns.fetch(:except) { [] } %>
<% _status = thing&.status || status %>
<% obj_path = thing ? thing.class.name.downcase.pluralize : local_assigns.fetch(:obj_path) { params[:controller] } %>
<% obj_class = obj_path.to_s.singularize.classify.constantize %>

<div class="badge <%= _status %>">
  <%= link_to send("#{obj_path}_path", with_existing_query(:status, _status).except(*except)) do %>
    <i class='<%= obj_class.status_icons(_status) %>'></i>
  <% end %>
</div>

app/views/shared/links/_timestamp.html.erb
<% use_highlight = local_assigns.fetch(:use_highlight) { true } %>
<% calendar_column = local_assigns.fetch(:calendar_column) { true } %>
<% color = local_assigns.fetch(:color) { 'red' } %>
<% obj_path = params[:controller] == 'plays' ? 'artists' : params[:controller] %>

<% if timestamp.present? %>
  <% if calendar_column %>
    <td>
      <span class='badge calendar-<%= color %>'>
        <%= link_to plays_path(date: (timestamp - 4.hours).strftime("%Y%m%d")) do %>
          <i class='fa-duotone fa-calendar-lines'></i>
        <% end %>
      </span>
    </td>
  <% end %>
  <% timestamp_class = 'mono' %>
  <% if use_highlight %>
    <% timestamp_distance = (Date.today - timestamp.to_date).to_i / 7 %>
    <% timestamp_distance = 0 if timestamp_distance < 0  %>
    <% timestamp_class += " recent#{timestamp_distance}" %>
  <% end %>
  <td class='last-played <%= timestamp_class %>'>
    <% year = timestamp.strftime('%Y') %>
    <% month = timestamp.strftime('%b') %>
    <% month_param = timestamp.strftime('%-m') %>
    <% day = timestamp.strftime('%d') %>
    <% day_param = timestamp.strftime('%-d') %>
    <% dow = timestamp.strftime('%a') %>
    <% dow_param = timestamp.strftime('%w') %>
    <% hour = timestamp.strftime('%H') %>
    <% minute = timestamp.strftime('%M') %>

    <% year_path = send("#{obj_path}_path", with_existing_query(:play_year, year).except(:play_month, :play_day)) %>
    <% month_path = send("#{obj_path}_path", with_existing_query.except(:order, :play_day).merge(play_year: year, play_month: month_param)) %>
    <% day_path = send("#{obj_path}_path", with_existing_query.except(:order).merge(play_year: year, play_month: month_param, play_day: day_param)) %>
    <% dow_path = send("#{obj_path}_path", with_existing_query(:play_dow, dow_param).except(:play_day)) %>
    <% hour_path = send("#{obj_path}_path", with_existing_query(:play_hour, hour)) %>

    <%= link_to year, year_path %> <%= link_to month, month_path %>-<%= link_to day, day_path %> <%= link_to dow, dow_path %> <%= link_to hour, hour_path %>:<%= minute %>
  </td>
<% else %>
  <% if calendar_column %>
    <td></td>
  <% end %>
  <td></td>
<% end %>

app/views/shared/links/_years.html.erb
<% if query[:year] %>
  <% years = query[:year].split(',').map(&:to_i).sort %>
  <section id='year-filters'>
    <h2 class='year'>
      <%= render partial: 'shared/links/delete', object: with_existing_query.except(:year) %>
      <% years_to_link = years.map {|i| [i-1,i,i+1]}.flatten.uniq %>
      <% years_to_link.each do |year| %>
        <% link_class = years.include?(year) ? 'bold' : 'diminished' %>
        <%= link_to year, send("#{params[:controller]}_path", with_existing_query(:year, year)), class: link_class %>
      <% end %>
    </h2>
  </section>
<% end %>