config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in', to: redirect('/'), as: :new_user_session
    get 'sign_out', to: redirect('/'), as: :destroy_user_session
  end

  root to: 'plays#index', date: 'today'

  get 'lf' => 'application#lastfm'
  post 'lf' => 'application#lastfm'
  get 'mb' => 'application#musicbrainz'

  resources :playlists, only: [:index, :show]
  resources :playlist_recordings, only: [:create]

  resources :plays, only: [:index, :create]

  resources :artists, only: [:show, :index, :update] do
    collection do
      get :roster
    end
  end

  resources :releases, only: [:show, :index, :update] do
    collection do
      get :search
      get :import
      post :import
    end
  end

  resources :recordings, only: [:index, :show, :update]
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_recordings
  has_many :recordings, through: :playlist_recordings

  validates_presence_of :name
  validates_uniqueness_of :name

  scope :for_index, -> {
    select(<<~SQL
      playlists.*,
      mode() within group (order by recordings.category) AS category
    SQL
    ).joins(<<~SQL
      INNER JOIN playlist_recordings pr ON pr.playlist_id = playlists.id
      INNER JOIN recordings             ON recordings.id  = pr.recording_id
    SQL
    ).group('playlists.id').from('playlists')
  }

  def length
    secs = recordings.sum(&:length) / 1000
    [[60, :seconds], [60, :minutes], [24, :hours], [1000, :days]].map{ |count, name|
      if secs > 0
        secs, n = secs.divmod(count)
        "#{n.to_i} #{name}"
      end
    }.compact.reverse.join(' ')
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.for_index.order('date DESC')
  end

  def show
    @playlist = Playlist.find(params[:id])
    @page_title = "Playlist > #{@playlist.name}"
    @recordings = Recording.for_playlist(@playlist)
  end
end

app/views/playlists/index.html.erb
<h2><%= @playlists.length %> playlists </h2>
<table>
  <% @playlists.each do |playlist| %>
    <tr>
      <td><%= link_to playlist.name, playlist_path(playlist) %></td>
      <td><div class='badge <%= Recording.categories.invert[playlist.category] %>'></div></td>
      <td><%= link_to playlist.playlist_recordings.find_by(position: 1)&.recording&.name, playlist_path(playlist) %></td>
      <td><%= playlist.date.strftime('%Y %B %d') if playlist.date.present? %></td>
      <td><%= playlist.recordings.count %> songs </td>
      <td><em><%= playlist.length %></em></td>
    </tr>
  <% end %>
</table>

app/views/playlists/show.html.erb
<h2><%= @playlist.name %></h2>
<h4><%= @playlist.date.strftime('%B %d, %Y') if @playlist.date.present? %></h4>

<table id='playlist-recordings'>
  <% if @recordings.any? %>
    <% max_plays = @recordings.max{|a,b| a.num_plays <=> b.num_plays}.num_plays %>
    <% max_width = max_plays > 10 ? max_plays : 10 %>
    <% @recordings.each do |recording| %>
      <tr>
        <td><%= recording.pos %></td>
        <td>(<%= link_to recording.id, lf_path(specific_id: recording.id, redirect: @current_path) %>)</td>
        <td><div class='badge <%= recording.category %>'></div></td>
        <td><%= link_to recording.artist_name, artist_path(recording.artist_id) %></td>
        <td><%= recording.name %></td>
        <%= render partial: 'shared/links/timestamp', object: recording.last_played %>
        <td><%= Recording.display_length(recording.length) %></td>
        <td>
          <% if recording.num_plays.to_i > 0 %>
            <div class='play_chart_container' style='width:<%= (recording.num_plays.to_i.to_f/max_width)*100+10 %>px'><%= recording.num_plays %></div>
          <% else %>
            0
          <% end %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <td>Nothing added.</td>
  <% end %>
</table>

<br>

<section>
  <%= form_for PlaylistRecording.new(playlist_id: @playlist.id, position: @playlist.recordings.count+1) do |f| %>
    <%= f.hidden_field :playlist_id %>
    <%= f.text_field :position %>
    <%= f.text_field :recording_id %>
    <%= f.submit %>
  <% end %>
</section>